# Name of workflow
name: Lint workflow

# Trigger the workflow on pull requests
on:
    pull_request:
        branches:
            - develop
            - staging

# Jobs to run
jobs:
    test:
        runs-on: ubuntu-latest
    
        # steps in job
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 21.x
              uses: actions/setup-node@v2 
              with:
                node-version: 21.x

            - name: 🧰 Install deps
              run: npm install

            - name: Run linting
              run: npm run lint
                